"""Type stubs for torch.nn module."""

from typing import Any, Optional, Tuple, Union, List
from .. import Tensor

# ---- Module base class ----

class Module:
    def __init__(self) -> None: ...
    def forward(self, *args: Any, **kwargs: Any) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameters(self) -> Any: ...
    def named_parameters(self) -> Any: ...
    def train(self, mode: bool = True) -> "Module": ...
    def eval(self) -> "Module": ...
    def to(self, device: Any) -> "Module": ...
    def state_dict(self) -> dict[str, Tensor]: ...
    def load_state_dict(self, state_dict: dict[str, Tensor]) -> None: ...

class Parameter(Tensor):
    def __init__(self, data: Tensor, requires_grad: bool = True) -> None: ...

# ---- Linear layers ----

class Linear(Module):
    weight: Tensor
    bias: Optional[Tensor]
    def __init__(self, in_features: int, out_features: int, bias: bool = True) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

# ---- Activation layers ----

class ReLU(Module):
    def __init__(self, inplace: bool = False) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class Sigmoid(Module):
    def forward(self, input: Tensor) -> Tensor: ...

class Tanh(Module):
    def forward(self, input: Tensor) -> Tensor: ...

class Softmax(Module):
    def __init__(self, dim: int) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class LogSoftmax(Module):
    def __init__(self, dim: int) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class GELU(Module):
    def forward(self, input: Tensor) -> Tensor: ...

class LeakyReLU(Module):
    def __init__(self, negative_slope: float = 0.01, inplace: bool = False) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

# ---- Loss functions ----

class MSELoss(Module):
    def __init__(self, reduction: str = "mean") -> None: ...
    def forward(self, input: Tensor, target: Tensor) -> Tensor: ...

class CrossEntropyLoss(Module):
    def __init__(self, weight: Optional[Tensor] = None, reduction: str = "mean") -> None: ...
    def forward(self, input: Tensor, target: Tensor) -> Tensor: ...

class BCELoss(Module):
    def __init__(self, weight: Optional[Tensor] = None, reduction: str = "mean") -> None: ...
    def forward(self, input: Tensor, target: Tensor) -> Tensor: ...

class L1Loss(Module):
    def __init__(self, reduction: str = "mean") -> None: ...
    def forward(self, input: Tensor, target: Tensor) -> Tensor: ...

class NLLLoss(Module):
    def __init__(self, weight: Optional[Tensor] = None, reduction: str = "mean") -> None: ...
    def forward(self, input: Tensor, target: Tensor) -> Tensor: ...

# ---- Normalization ----

class BatchNorm1d(Module):
    def __init__(self, num_features: int) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class BatchNorm2d(Module):
    def __init__(self, num_features: int) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class LayerNorm(Module):
    def __init__(self, normalized_shape: Union[int, List[int]], eps: float = 1e-5) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

# ---- Dropout ----

class Dropout(Module):
    def __init__(self, p: float = 0.5, inplace: bool = False) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

# ---- Convolution ----

class Conv1d(Module):
    weight: Tensor
    bias: Optional[Tensor]
    def __init__(self, in_channels: int, out_channels: int, kernel_size: int, stride: int = 1, padding: int = 0, bias: bool = True) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class Conv2d(Module):
    weight: Tensor
    bias: Optional[Tensor]
    def __init__(self, in_channels: int, out_channels: int, kernel_size: Union[int, Tuple[int, int]], stride: Union[int, Tuple[int, int]] = 1, padding: Union[int, Tuple[int, int]] = 0, bias: bool = True) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

# ---- Pooling ----

class MaxPool2d(Module):
    def __init__(self, kernel_size: Union[int, Tuple[int, int]], stride: Optional[Union[int, Tuple[int, int]]] = None, padding: Union[int, Tuple[int, int]] = 0) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class AvgPool2d(Module):
    def __init__(self, kernel_size: Union[int, Tuple[int, int]], stride: Optional[Union[int, Tuple[int, int]]] = None, padding: Union[int, Tuple[int, int]] = 0) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

# ---- RNN ----

class RNN(Module):
    def __init__(self, input_size: int, hidden_size: int, num_layers: int = 1, batch_first: bool = False, bidirectional: bool = False) -> None: ...
    def forward(self, input: Tensor, hx: Optional[Tensor] = None) -> Tuple[Tensor, Tensor]: ...

class LSTM(Module):
    def __init__(self, input_size: int, hidden_size: int, num_layers: int = 1, batch_first: bool = False, bidirectional: bool = False) -> None: ...
    def forward(self, input: Tensor, hx: Optional[Tuple[Tensor, Tensor]] = None) -> Tuple[Tensor, Tuple[Tensor, Tensor]]: ...

class GRU(Module):
    def __init__(self, input_size: int, hidden_size: int, num_layers: int = 1, batch_first: bool = False, bidirectional: bool = False) -> None: ...
    def forward(self, input: Tensor, hx: Optional[Tensor] = None) -> Tuple[Tensor, Tensor]: ...

# ---- Embedding ----

class Embedding(Module):
    weight: Tensor
    def __init__(self, num_embeddings: int, embedding_dim: int, padding_idx: Optional[int] = None) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

# ---- Sequential ----

class Sequential(Module):
    def __init__(self, *args: Module) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

# ---- Functional submodule ----

from . import functional as functional
