"""Type stubs for torch.nn.functional module."""

from typing import Optional, Tuple, Union
from .. import Tensor

# ---- Activation functions ----

def relu(input: Tensor, inplace: bool = False) -> Tensor: ...
def leaky_relu(input: Tensor, negative_slope: float = 0.01, inplace: bool = False) -> Tensor: ...
def gelu(input: Tensor) -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def softmax(input: Tensor, dim: int) -> Tensor: ...
def log_softmax(input: Tensor, dim: int) -> Tensor: ...
def softplus(input: Tensor, beta: float = 1.0, threshold: float = 20.0) -> Tensor: ...
def silu(input: Tensor, inplace: bool = False) -> Tensor: ...
def elu(input: Tensor, alpha: float = 1.0, inplace: bool = False) -> Tensor: ...

# ---- Loss functions ----

def mse_loss(input: Tensor, target: Tensor, reduction: str = "mean") -> Tensor: ...
def cross_entropy(input: Tensor, target: Tensor, weight: Optional[Tensor] = None, reduction: str = "mean") -> Tensor: ...
def binary_cross_entropy(input: Tensor, target: Tensor, weight: Optional[Tensor] = None, reduction: str = "mean") -> Tensor: ...
def l1_loss(input: Tensor, target: Tensor, reduction: str = "mean") -> Tensor: ...
def nll_loss(input: Tensor, target: Tensor, weight: Optional[Tensor] = None, reduction: str = "mean") -> Tensor: ...
def smooth_l1_loss(input: Tensor, target: Tensor, reduction: str = "mean", beta: float = 1.0) -> Tensor: ...

# ---- Linear ----

def linear(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None) -> Tensor: ...

# ---- Dropout ----

def dropout(input: Tensor, p: float = 0.5, training: bool = True, inplace: bool = False) -> Tensor: ...

# ---- Convolution ----

def conv1d(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None, stride: int = 1, padding: int = 0) -> Tensor: ...
def conv2d(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None, stride: Union[int, Tuple[int, int]] = 1, padding: Union[int, Tuple[int, int]] = 0) -> Tensor: ...

# ---- Pooling ----

def max_pool2d(input: Tensor, kernel_size: Union[int, Tuple[int, int]], stride: Optional[Union[int, Tuple[int, int]]] = None, padding: Union[int, Tuple[int, int]] = 0) -> Tensor: ...
def avg_pool2d(input: Tensor, kernel_size: Union[int, Tuple[int, int]], stride: Optional[Union[int, Tuple[int, int]]] = None, padding: Union[int, Tuple[int, int]] = 0) -> Tensor: ...
def adaptive_avg_pool2d(input: Tensor, output_size: Union[int, Tuple[int, int]]) -> Tensor: ...

# ---- Normalization ----

def batch_norm(input: Tensor, running_mean: Optional[Tensor], running_var: Optional[Tensor], weight: Optional[Tensor] = None, bias: Optional[Tensor] = None, training: bool = False, momentum: float = 0.1, eps: float = 1e-5) -> Tensor: ...
def layer_norm(input: Tensor, normalized_shape: list[int], weight: Optional[Tensor] = None, bias: Optional[Tensor] = None, eps: float = 1e-5) -> Tensor: ...

# ---- Misc ----

def pad(input: Tensor, pad: Tuple[int, ...], mode: str = "constant", value: float = 0.0) -> Tensor: ...
def interpolate(input: Tensor, size: Optional[Union[int, Tuple[int, ...]]] = None, scale_factor: Optional[Union[float, Tuple[float, ...]]] = None, mode: str = "nearest") -> Tensor: ...
def one_hot(tensor: Tensor, num_classes: int = -1) -> Tensor: ...
