/**
 * VS Code "Dark Modern" theme adapted for Monaco editor.
 * Inherits from vs-dark for base tokenization colors, adds Dark Modern
 * editor chrome and semantic token rules for ty.
 */

// Semantic token rules for ty — both PascalCase (enum names) and lowercase
// (LSP standard) since we don't know which format ty.SemanticToken.kinds() returns.
export const darkSemanticRules = [
  { token: "Namespace", foreground: "4ec9b0" },
  { token: "namespace", foreground: "4ec9b0" },
  { token: "Class", foreground: "4ec9b0" },
  { token: "class", foreground: "4ec9b0" },
  { token: "Parameter", foreground: "9cdcfe" },
  { token: "parameter", foreground: "9cdcfe" },
  { token: "SelfParameter", foreground: "569cd6", fontStyle: "italic" },
  { token: "selfParameter", foreground: "569cd6", fontStyle: "italic" },
  { token: "ClsParameter", foreground: "569cd6", fontStyle: "italic" },
  { token: "clsParameter", foreground: "569cd6", fontStyle: "italic" },
  { token: "Variable", foreground: "9cdcfe" },
  { token: "variable", foreground: "9cdcfe" },
  { token: "Property", foreground: "9cdcfe" },
  { token: "property", foreground: "9cdcfe" },
  { token: "Function", foreground: "dcdcaa" },
  { token: "function", foreground: "dcdcaa" },
  { token: "Method", foreground: "dcdcaa" },
  { token: "method", foreground: "dcdcaa" },
  { token: "Keyword", foreground: "569cd6" },
  { token: "keyword", foreground: "569cd6" },
  { token: "String", foreground: "ce9178" },
  { token: "Number", foreground: "b5cea8" },
  { token: "Decorator", foreground: "dcdcaa", fontStyle: "italic" },
  { token: "decorator", foreground: "dcdcaa", fontStyle: "italic" },
  { token: "BuiltinConstant", foreground: "569cd6" },
  { token: "builtinConstant", foreground: "569cd6" },
  { token: "TypeParameter", foreground: "4ec9b0" },
  { token: "typeParameter", foreground: "4ec9b0" },
  // Operator token (for our custom monarch rule)
  { token: "operator", foreground: "d4d4d4" },
  { token: "operator.python", foreground: "d4d4d4" },
];

export const lightSemanticRules = [
  { token: "Namespace", foreground: "267f99" },
  { token: "namespace", foreground: "267f99" },
  { token: "Class", foreground: "267f99" },
  { token: "class", foreground: "267f99" },
  { token: "Parameter", foreground: "001080" },
  { token: "parameter", foreground: "001080" },
  { token: "SelfParameter", foreground: "0000ff", fontStyle: "italic" },
  { token: "selfParameter", foreground: "0000ff", fontStyle: "italic" },
  { token: "ClsParameter", foreground: "0000ff", fontStyle: "italic" },
  { token: "clsParameter", foreground: "0000ff", fontStyle: "italic" },
  { token: "Variable", foreground: "001080" },
  { token: "variable", foreground: "001080" },
  { token: "Property", foreground: "001080" },
  { token: "property", foreground: "001080" },
  { token: "Function", foreground: "795e26" },
  { token: "function", foreground: "795e26" },
  { token: "Method", foreground: "795e26" },
  { token: "method", foreground: "795e26" },
  { token: "Keyword", foreground: "0000ff" },
  { token: "keyword", foreground: "0000ff" },
  { token: "String", foreground: "a31515" },
  { token: "Number", foreground: "098658" },
  { token: "Decorator", foreground: "795e26", fontStyle: "italic" },
  { token: "decorator", foreground: "795e26", fontStyle: "italic" },
  { token: "BuiltinConstant", foreground: "0000ff" },
  { token: "builtinConstant", foreground: "0000ff" },
  { token: "TypeParameter", foreground: "267f99" },
  { token: "typeParameter", foreground: "267f99" },
  { token: "operator", foreground: "000000" },
  { token: "operator.python", foreground: "000000" },
];

export const darkModernTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: darkSemanticRules,
  colors: {
    "editor.background": "#1f1f1f",
    "editor.foreground": "#cccccc",
    "editorLineNumber.foreground": "#6e7681",
    "editorLineNumber.activeForeground": "#cccccc",
    "editor.selectionBackground": "#264f78",
    "editor.inactiveSelectionBackground": "#3a3d41",
    "editor.lineHighlightBackground": "#2a2d2e",
    "editor.lineHighlightBorder": "#00000000",
    "editorCursor.foreground": "#aeafad",
    "editorWidget.background": "#252526",
    "editorWidget.border": "#454545",
    "editorSuggestWidget.background": "#252526",
    "editorSuggestWidget.border": "#454545",
    "editorSuggestWidget.selectedBackground": "#04395e",
    "editorHoverWidget.background": "#252526",
    "editorHoverWidget.border": "#454545",
    "scrollbarSlider.background": "#79797966",
    "scrollbarSlider.hoverBackground": "#646464b3",
    "scrollbarSlider.activeBackground": "#bfbfbf66",
    "editorOverviewRuler.border": "#00000000",
    "editorGutter.background": "#1f1f1f",
  },
};

export const lightModernTheme = {
  base: "vs" as const,
  inherit: true,
  rules: lightSemanticRules,
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#3b3b3b",
    "editorLineNumber.foreground": "#6e7681",
    "editorLineNumber.activeForeground": "#171184",
    "editor.selectionBackground": "#add6ff",
    "editor.inactiveSelectionBackground": "#e5ebf1",
    "editor.lineHighlightBackground": "#f0f0f0",
    "editor.lineHighlightBorder": "#00000000",
    "editorCursor.foreground": "#000000",
    "editorWidget.background": "#f3f3f3",
    "editorWidget.border": "#c8c8c8",
    "editorSuggestWidget.background": "#f3f3f3",
    "editorSuggestWidget.border": "#c8c8c8",
    "editorSuggestWidget.selectedBackground": "#d6ebff",
    "editorHoverWidget.background": "#f3f3f3",
    "editorHoverWidget.border": "#c8c8c8",
    "scrollbarSlider.background": "#79797966",
    "scrollbarSlider.hoverBackground": "#646464b3",
    "scrollbarSlider.activeBackground": "#bfbfbf66",
    "editorOverviewRuler.border": "#00000000",
    "editorGutter.background": "#ffffff",
  },
};

/**
 * Replace Monaco's built-in Python monarch tokenizer with one that
 * also tokenizes operators. Call after Monaco is loaded.
 */
export function enhancePythonTokenizer(monaco: typeof import("monaco-editor")) {
  monaco.languages.setMonarchTokensProvider("python", {
    defaultToken: "",
    tokenPostfix: ".python",
    keywords: [
      "False", "None", "True", "_",
      "and", "as", "assert", "async", "await", "break", "case", "class",
      "continue", "def", "del", "elif", "else", "except", "exec", "finally",
      "for", "from", "global", "if", "import", "in", "is", "lambda", "match",
      "nonlocal", "not", "or", "pass", "print", "raise", "return", "try",
      "type", "while", "with", "yield",
    ],
    builtins: [
      "int", "float", "long", "complex", "hex", "abs", "all", "any", "apply",
      "basestring", "bin", "bool", "buffer", "bytearray", "callable", "chr",
      "classmethod", "cmp", "coerce", "compile", "complex", "delattr", "dict",
      "dir", "divmod", "enumerate", "eval", "execfile", "file", "filter",
      "format", "frozenset", "getattr", "globals", "hasattr", "hash", "help",
      "id", "input", "intern", "isinstance", "issubclass", "iter", "len",
      "locals", "list", "map", "max", "memoryview", "min", "next", "object",
      "oct", "open", "ord", "pow", "print", "property", "reversed", "range",
      "raw_input", "reduce", "reload", "repr", "reversed", "round", "self",
      "set", "setattr", "slice", "sorted", "staticmethod", "str", "sum",
      "super", "tuple", "type", "unichr", "unicode", "vars", "xrange", "zip",
      "__dict__", "__methods__", "__members__", "__class__", "__bases__",
      "__name__", "__mro__", "__subclasses__", "__init__", "__import__",
    ],
    brackets: [
      { open: "{", close: "}", token: "delimiter.curly" },
      { open: "[", close: "]", token: "delimiter.bracket" },
      { open: "(", close: ")", token: "delimiter.parenthesis" },
    ],
    tokenizer: {
      root: [
        { include: "@whitespace" },
        { include: "@numbers" },
        { include: "@strings" },
        // Operators — must come before identifier/keyword rules
        [/->|\.\.\./, "operator"],
        [/\*\*=?/, "operator"],
        [/\/\/=?/, "operator"],
        [/<<=?|>>=?/, "operator"],
        [/[+\-*/%&|^~<>!=@]=?/, "operator"],
        [/[,:;]/, "delimiter"],
        [/[{}\[\]()]/, "@brackets"],
        [/@[a-zA-Z_]\w*/, "tag"],
        [/[a-zA-Z_]\w*/, {
          cases: {
            "@keywords": "keyword",
            "@builtins": "predefined",
            "@default": "identifier",
          },
        }],
      ],
      whitespace: [
        [/\s+/, "white"],
        [/(^#.*$)/, "comment"],
        [/'''/, "string", "@endDocString"],
        [/"""/, "string", "@endDblDocString"],
      ],
      endDocString: [
        [/[^']+/, "string"],
        [/\\'/, "string"],
        [/'''/, "string", "@popall"],
        [/'/, "string"],
      ],
      endDblDocString: [
        [/[^"]+/, "string"],
        [/\\"/, "string"],
        [/"""/, "string", "@popall"],
        [/"/, "string"],
      ],
      numbers: [
        [/-?0x([abcdef]|[ABCDEF]|\d)+[lL]?/, "number.hex"],
        [/-?(\d*\.)?\d+([eE][+-]?\d+)?[jJ]?[lL]?/, "number"],
      ],
      strings: [
        [/'$/, "string.escape", "@popall"],
        [/f'{1,3}/, "string.escape", "@fStringBody"],
        [/'/, "string.escape", "@stringBody"],
        [/"$/, "string.escape", "@popall"],
        [/f"{1,3}/, "string.escape", "@fDblStringBody"],
        [/"/, "string.escape", "@dblStringBody"],
      ],
      fStringBody: [
        [/[^\\'\{\}]+$/, "string", "@popall"],
        [/[^\\'\{\}]+/, "string"],
        [/\{[^\}':!=]+/, "identifier", "@fStringDetail"],
        [/\\./, "string"],
        [/'/, "string.escape", "@popall"],
        [/\\$/, "string"],
      ],
      stringBody: [
        [/[^\\']+$/, "string", "@popall"],
        [/[^\\']+/, "string"],
        [/\\./, "string"],
        [/'/, "string.escape", "@popall"],
        [/\\$/, "string"],
      ],
      fDblStringBody: [
        [/[^\\"\{\}]+$/, "string", "@popall"],
        [/[^\\"\{\}]+/, "string"],
        [/\{[^\}':!=]+/, "identifier", "@fStringDetail"],
        [/\\./, "string"],
        [/"/, "string.escape", "@popall"],
        [/\\$/, "string"],
      ],
      dblStringBody: [
        [/[^\\"]+$/, "string", "@popall"],
        [/[^\\"]+/, "string"],
        [/\\./, "string"],
        [/"/, "string.escape", "@popall"],
        [/\\$/, "string"],
      ],
      fStringDetail: [
        [/[:][^}]+/, "string"],
        [/[!][ars]/, "string"],
        [/=/, "string"],
        [/\}/, "identifier", "@pop"],
      ],
    },
  } as any);
}
