"""Type stubs for PyTorch torch module."""

from typing import (
    Any,
    Iterator,
    Optional,
    Sequence,
    Tuple,
    Union,
    overload,
    List,
)

# ---- dtype ----

class dtype:
    """Represents a tensor element data type."""
    ...

float16: dtype
float32: dtype
float64: dtype
bfloat16: dtype
half: dtype
float: dtype
double: dtype
int8: dtype
int16: dtype
int32: dtype
int64: dtype
short: dtype
int: dtype
long: dtype
uint8: dtype
bool: dtype
complex64: dtype
complex128: dtype

# ---- Size (shape) ----

class Size(Tuple[int, ...]):
    def numel(self) -> int: ...

# ---- device ----

class device:
    def __init__(self, type: str, index: Optional[int] = None) -> None: ...

# ---- Tensor ----

_ShapeLike = Union[Tuple[int, ...], List[int], "Size"]
_ScalarLike = Union[int, float, bool]
_TensorOrScalar = Union["Tensor", _ScalarLike]
_DTypeLike = Optional[dtype]

class Tensor:
    """Multi-dimensional matrix containing elements of a single data type."""

    # --- Properties ---
    @property
    def shape(self) -> Size: ...
    @property
    def dtype(self) -> dtype: ...
    @property
    def device(self) -> device: ...
    @property
    def ndim(self) -> int: ...
    @property
    def T(self) -> "Tensor": ...
    @property
    def data(self) -> "Tensor": ...
    @property
    def grad(self) -> Optional["Tensor"]: ...
    @property
    def requires_grad(self) -> bool: ...
    @requires_grad.setter
    def requires_grad(self, value: bool) -> None: ...

    # --- Shape manipulation ---
    def size(self, dim: Optional[int] = None) -> Union[Size, int]: ...
    def dim(self) -> int: ...
    def numel(self) -> int: ...
    def reshape(self, *shape: int) -> "Tensor": ...
    def view(self, *shape: int) -> "Tensor": ...
    def transpose(self, dim0: int, dim1: int) -> "Tensor": ...
    def permute(self, *dims: int) -> "Tensor": ...
    def unsqueeze(self, dim: int) -> "Tensor": ...
    def squeeze(self, dim: Optional[int] = None) -> "Tensor": ...
    def flatten(self, start_dim: int = 0, end_dim: int = -1) -> "Tensor": ...
    def expand(self, *sizes: int) -> "Tensor": ...
    def expand_as(self, other: "Tensor") -> "Tensor": ...
    def repeat(self, *sizes: int) -> "Tensor": ...
    def contiguous(self) -> "Tensor": ...
    def t(self) -> "Tensor": ...
    def narrow(self, dim: int, start: int, length: int) -> "Tensor": ...
    def chunk(self, chunks: int, dim: int = 0) -> Tuple["Tensor", ...]: ...
    def split(self, split_size: Union[int, List[int]], dim: int = 0) -> Tuple["Tensor", ...]: ...

    # --- Indexing ---
    def __getitem__(self, index: Any) -> "Tensor": ...
    def __setitem__(self, index: Any, value: _TensorOrScalar) -> None: ...

    # --- Arithmetic operators ---
    def __add__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __radd__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __iadd__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __sub__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __rsub__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __isub__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __mul__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __rmul__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __imul__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __truediv__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __rtruediv__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __itruediv__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __floordiv__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __mod__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __pow__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __matmul__(self, other: "Tensor") -> "Tensor": ...
    def __rmatmul__(self, other: "Tensor") -> "Tensor": ...
    def __neg__(self) -> "Tensor": ...
    def __abs__(self) -> "Tensor": ...

    # --- Comparison operators ---
    def __eq__(self, other: _TensorOrScalar) -> "Tensor": ...  # type: ignore[override]
    def __ne__(self, other: _TensorOrScalar) -> "Tensor": ...  # type: ignore[override]
    def __lt__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __le__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __gt__(self, other: _TensorOrScalar) -> "Tensor": ...
    def __ge__(self, other: _TensorOrScalar) -> "Tensor": ...

    # --- Unary / conversion ---
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator["Tensor"]: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...

    # --- Reduction operations ---
    def sum(self, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False) -> "Tensor": ...
    def mean(self, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False) -> "Tensor": ...
    def max(self, dim: Optional[int] = None, keepdim: bool = False) -> Union["Tensor", Tuple["Tensor", "Tensor"]]: ...
    def min(self, dim: Optional[int] = None, keepdim: bool = False) -> Union["Tensor", Tuple["Tensor", "Tensor"]]: ...
    def prod(self, dim: Optional[int] = None, keepdim: bool = False) -> "Tensor": ...
    def std(self, dim: Optional[Union[int, Tuple[int, ...]]] = None, unbiased: bool = True, keepdim: bool = False) -> "Tensor": ...
    def var(self, dim: Optional[Union[int, Tuple[int, ...]]] = None, unbiased: bool = True, keepdim: bool = False) -> "Tensor": ...
    def norm(self, p: _TensorOrScalar = 2, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False) -> "Tensor": ...
    def argmax(self, dim: Optional[int] = None, keepdim: bool = False) -> "Tensor": ...
    def argmin(self, dim: Optional[int] = None, keepdim: bool = False) -> "Tensor": ...
    def all(self, dim: Optional[int] = None, keepdim: bool = False) -> "Tensor": ...
    def any(self, dim: Optional[int] = None, keepdim: bool = False) -> "Tensor": ...
    def cumsum(self, dim: int) -> "Tensor": ...
    def cumprod(self, dim: int) -> "Tensor": ...

    # --- Math operations ---
    def abs(self) -> "Tensor": ...
    def sqrt(self) -> "Tensor": ...
    def exp(self) -> "Tensor": ...
    def log(self) -> "Tensor": ...
    def pow(self, exponent: _TensorOrScalar) -> "Tensor": ...
    def clamp(self, min: Optional[float] = None, max: Optional[float] = None) -> "Tensor": ...
    def clip(self, min: Optional[float] = None, max: Optional[float] = None) -> "Tensor": ...
    def ceil(self) -> "Tensor": ...
    def floor(self) -> "Tensor": ...
    def round(self) -> "Tensor": ...
    def sign(self) -> "Tensor": ...
    def sin(self) -> "Tensor": ...
    def cos(self) -> "Tensor": ...
    def tan(self) -> "Tensor": ...
    def sigmoid(self) -> "Tensor": ...
    def softmax(self, dim: int) -> "Tensor": ...
    def log_softmax(self, dim: int) -> "Tensor": ...
    def relu(self) -> "Tensor": ...

    # --- Linear algebra ---
    def matmul(self, other: "Tensor") -> "Tensor": ...
    def mm(self, other: "Tensor") -> "Tensor": ...
    def bmm(self, other: "Tensor") -> "Tensor": ...
    def dot(self, other: "Tensor") -> "Tensor": ...
    def cross(self, other: "Tensor", dim: int = -1) -> "Tensor": ...
    def inverse(self) -> "Tensor": ...
    def det(self) -> "Tensor": ...
    def trace(self) -> "Tensor": ...
    def diag(self, diagonal: int = 0) -> "Tensor": ...
    def diagonal(self, offset: int = 0, dim1: int = 0, dim2: int = 1) -> "Tensor": ...
    def triu(self, diagonal: int = 0) -> "Tensor": ...
    def tril(self, diagonal: int = 0) -> "Tensor": ...
    def svd(self) -> Tuple["Tensor", "Tensor", "Tensor"]: ...
    def eig(self) -> Tuple["Tensor", "Tensor"]: ...

    # --- Comparison ---
    def eq(self, other: _TensorOrScalar) -> "Tensor": ...
    def ne(self, other: _TensorOrScalar) -> "Tensor": ...
    def lt(self, other: _TensorOrScalar) -> "Tensor": ...
    def le(self, other: _TensorOrScalar) -> "Tensor": ...
    def gt(self, other: _TensorOrScalar) -> "Tensor": ...
    def ge(self, other: _TensorOrScalar) -> "Tensor": ...
    def isnan(self) -> "Tensor": ...
    def isinf(self) -> "Tensor": ...

    # --- Type / device ---
    def to(self, device_or_dtype: Union[device, dtype, str], **kwargs: Any) -> "Tensor": ...
    def cpu(self) -> "Tensor": ...
    def cuda(self, device: Optional[Union[device, int]] = None) -> "Tensor": ...
    def type(self, dtype: Optional[Union[str, dtype]] = None) -> Union["Tensor", str]: ...
    def float(self) -> "Tensor": ...
    def double(self) -> "Tensor": ...
    def half(self) -> "Tensor": ...
    def int(self) -> "Tensor": ...
    def long(self) -> "Tensor": ...
    def bool(self) -> "Tensor": ...
    def is_floating_point(self) -> bool: ...

    # --- Copy / clone ---
    def clone(self) -> "Tensor": ...
    def detach(self) -> "Tensor": ...
    def numpy(self) -> Any: ...
    def tolist(self) -> Any: ...
    def item(self) -> Union[int, float, bool]: ...

    # --- In-place ---
    def fill_(self, value: _ScalarLike) -> "Tensor": ...
    def zero_(self) -> "Tensor": ...
    def uniform_(self, from_: float = 0.0, to: float = 1.0) -> "Tensor": ...
    def normal_(self, mean: float = 0.0, std: float = 1.0) -> "Tensor": ...
    def copy_(self, src: "Tensor") -> "Tensor": ...
    def clamp_(self, min: Optional[float] = None, max: Optional[float] = None) -> "Tensor": ...
    def add_(self, other: _TensorOrScalar) -> "Tensor": ...
    def sub_(self, other: _TensorOrScalar) -> "Tensor": ...
    def mul_(self, other: _TensorOrScalar) -> "Tensor": ...
    def div_(self, other: _TensorOrScalar) -> "Tensor": ...

    # --- Sorting ---
    def sort(self, dim: int = -1, descending: bool = False) -> Tuple["Tensor", "Tensor"]: ...
    def topk(self, k: int, dim: int = -1, largest: bool = True, sorted: bool = True) -> Tuple["Tensor", "Tensor"]: ...
    def argsort(self, dim: int = -1, descending: bool = False) -> "Tensor": ...

    # --- Misc ---
    def masked_fill(self, mask: "Tensor", value: _ScalarLike) -> "Tensor": ...
    def masked_fill_(self, mask: "Tensor", value: _ScalarLike) -> "Tensor": ...
    def masked_select(self, mask: "Tensor") -> "Tensor": ...
    def where(self, condition: "Tensor", other: _TensorOrScalar) -> "Tensor": ...
    def gather(self, dim: int, index: "Tensor") -> "Tensor": ...
    def scatter(self, dim: int, index: "Tensor", src: _TensorOrScalar) -> "Tensor": ...
    def scatter_(self, dim: int, index: "Tensor", src: _TensorOrScalar) -> "Tensor": ...
    def index_select(self, dim: int, index: "Tensor") -> "Tensor": ...
    def nonzero(self) -> "Tensor": ...
    def unique(self, sorted: bool = True, return_inverse: bool = False, return_counts: bool = False) -> Union["Tensor", Tuple["Tensor", ...]]: ...
    def flip(self, dims: Union[int, Tuple[int, ...]]) -> "Tensor": ...
    def roll(self, shifts: Union[int, Tuple[int, ...]], dims: Optional[Union[int, Tuple[int, ...]]] = None) -> "Tensor": ...
    def requires_grad_(self, requires_grad: bool = True) -> "Tensor": ...
    def backward(self, gradient: Optional["Tensor"] = None) -> None: ...

# ---- Creation functions ----

_InputData = Union[_ScalarLike, Sequence[Any], "Tensor"]

def tensor(data: _InputData, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def zeros(*size: int, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def ones(*size: int, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def empty(*size: int, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def full(size: _ShapeLike, fill_value: _ScalarLike, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def randn(*size: int, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def rand(*size: int, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def randint(low: int, high: int, size: _ShapeLike, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def arange(start: _ScalarLike, end: Optional[_ScalarLike] = None, step: _ScalarLike = 1, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def linspace(start: _ScalarLike, end: _ScalarLike, steps: int, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def logspace(start: _ScalarLike, end: _ScalarLike, steps: int, base: float = 10.0, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def eye(n: int, m: Optional[int] = None, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def zeros_like(input: Tensor, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def ones_like(input: Tensor, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def empty_like(input: Tensor, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def rand_like(input: Tensor, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def randn_like(input: Tensor, dtype: _DTypeLike = None, device: Optional[Union[device, str]] = None, requires_grad: bool = False) -> Tensor: ...
def from_numpy(ndarray: Any) -> Tensor: ...

# ---- Math functions ----

def matmul(input: Tensor, other: Tensor) -> Tensor: ...
def mm(input: Tensor, mat2: Tensor) -> Tensor: ...
def bmm(input: Tensor, mat2: Tensor) -> Tensor: ...
def dot(input: Tensor, other: Tensor) -> Tensor: ...
def cross(input: Tensor, other: Tensor, dim: int = -1) -> Tensor: ...
def abs(input: Tensor) -> Tensor: ...
def sqrt(input: Tensor) -> Tensor: ...
def exp(input: Tensor) -> Tensor: ...
def log(input: Tensor) -> Tensor: ...
def log2(input: Tensor) -> Tensor: ...
def log10(input: Tensor) -> Tensor: ...
def pow(input: Tensor, exponent: _TensorOrScalar) -> Tensor: ...
def clamp(input: Tensor, min: Optional[float] = None, max: Optional[float] = None) -> Tensor: ...
def clip(input: Tensor, min: Optional[float] = None, max: Optional[float] = None) -> Tensor: ...
def ceil(input: Tensor) -> Tensor: ...
def floor(input: Tensor) -> Tensor: ...
def round(input: Tensor) -> Tensor: ...
def sign(input: Tensor) -> Tensor: ...
def sin(input: Tensor) -> Tensor: ...
def cos(input: Tensor) -> Tensor: ...
def tan(input: Tensor) -> Tensor: ...
def asin(input: Tensor) -> Tensor: ...
def acos(input: Tensor) -> Tensor: ...
def atan(input: Tensor) -> Tensor: ...
def atan2(input: Tensor, other: Tensor) -> Tensor: ...
def sinh(input: Tensor) -> Tensor: ...
def cosh(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def relu(input: Tensor) -> Tensor: ...
def softmax(input: Tensor, dim: int) -> Tensor: ...
def log_softmax(input: Tensor, dim: int) -> Tensor: ...

# ---- Reduction functions ----

def sum(input: Tensor, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False) -> Tensor: ...
def mean(input: Tensor, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False) -> Tensor: ...
def max(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Union[Tensor, Tuple[Tensor, Tensor]]: ...
def min(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Union[Tensor, Tuple[Tensor, Tensor]]: ...
def prod(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def std(input: Tensor, dim: Optional[Union[int, Tuple[int, ...]]] = None, unbiased: bool = True, keepdim: bool = False) -> Tensor: ...
def var(input: Tensor, dim: Optional[Union[int, Tuple[int, ...]]] = None, unbiased: bool = True, keepdim: bool = False) -> Tensor: ...
def norm(input: Tensor, p: _TensorOrScalar = 2, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False) -> Tensor: ...
def argmax(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def argmin(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def cumsum(input: Tensor, dim: int) -> Tensor: ...
def cumprod(input: Tensor, dim: int) -> Tensor: ...

# ---- Tensor manipulation ----

def cat(tensors: Union[Tuple[Tensor, ...], List[Tensor]], dim: int = 0) -> Tensor: ...
def stack(tensors: Union[Tuple[Tensor, ...], List[Tensor]], dim: int = 0) -> Tensor: ...
def split(tensor: Tensor, split_size_or_sections: Union[int, List[int]], dim: int = 0) -> Tuple[Tensor, ...]: ...
def chunk(input: Tensor, chunks: int, dim: int = 0) -> Tuple[Tensor, ...]: ...
def squeeze(input: Tensor, dim: Optional[int] = None) -> Tensor: ...
def unsqueeze(input: Tensor, dim: int) -> Tensor: ...
def reshape(input: Tensor, shape: _ShapeLike) -> Tensor: ...
def transpose(input: Tensor, dim0: int, dim1: int) -> Tensor: ...
def permute(input: Tensor, dims: Tuple[int, ...]) -> Tensor: ...
def flatten(input: Tensor, start_dim: int = 0, end_dim: int = -1) -> Tensor: ...
def flip(input: Tensor, dims: Union[int, Tuple[int, ...]]) -> Tensor: ...
def roll(input: Tensor, shifts: Union[int, Tuple[int, ...]], dims: Optional[Union[int, Tuple[int, ...]]] = None) -> Tensor: ...
def repeat_interleave(input: Tensor, repeats: Union[int, Tensor], dim: Optional[int] = None) -> Tensor: ...
def tile(input: Tensor, dims: Tuple[int, ...]) -> Tensor: ...

# ---- Comparison & logical ----

def eq(input: Tensor, other: _TensorOrScalar) -> Tensor: ...
def ne(input: Tensor, other: _TensorOrScalar) -> Tensor: ...
def lt(input: Tensor, other: _TensorOrScalar) -> Tensor: ...
def le(input: Tensor, other: _TensorOrScalar) -> Tensor: ...
def gt(input: Tensor, other: _TensorOrScalar) -> Tensor: ...
def ge(input: Tensor, other: _TensorOrScalar) -> Tensor: ...
def isnan(input: Tensor) -> Tensor: ...
def isinf(input: Tensor) -> Tensor: ...
def isfinite(input: Tensor) -> Tensor: ...
def where(condition: Tensor, input: _TensorOrScalar, other: _TensorOrScalar) -> Tensor: ...
def all(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...
def any(input: Tensor, dim: Optional[int] = None, keepdim: bool = False) -> Tensor: ...

# ---- Sorting & selection ----

def sort(input: Tensor, dim: int = -1, descending: bool = False) -> Tuple[Tensor, Tensor]: ...
def topk(input: Tensor, k: int, dim: int = -1, largest: bool = True, sorted: bool = True) -> Tuple[Tensor, Tensor]: ...
def argsort(input: Tensor, dim: int = -1, descending: bool = False) -> Tensor: ...
def gather(input: Tensor, dim: int, index: Tensor) -> Tensor: ...
def scatter(input: Tensor, dim: int, index: Tensor, src: _TensorOrScalar) -> Tensor: ...
def index_select(input: Tensor, dim: int, index: Tensor) -> Tensor: ...
def masked_select(input: Tensor, mask: Tensor) -> Tensor: ...
def nonzero(input: Tensor) -> Tensor: ...
def unique(input: Tensor, sorted: bool = True, return_inverse: bool = False, return_counts: bool = False) -> Union[Tensor, Tuple[Tensor, ...]]: ...

# ---- Linear algebra (top-level) ----

def trace(input: Tensor) -> Tensor: ...
def diag(input: Tensor, diagonal: int = 0) -> Tensor: ...
def diagonal(input: Tensor, offset: int = 0, dim1: int = 0, dim2: int = 1) -> Tensor: ...
def triu(input: Tensor, diagonal: int = 0) -> Tensor: ...
def tril(input: Tensor, diagonal: int = 0) -> Tensor: ...
def einsum(equation: str, *operands: Tensor) -> Tensor: ...

# ---- Misc ----

def no_grad() -> Any: ...
def enable_grad() -> Any: ...
def is_tensor(obj: Any) -> bool: ...
def manual_seed(seed: int) -> Any: ...

# ---- Submodules ----

from . import linalg as linalg
from . import nn as nn
