"""Type stubs for torch.linalg module."""

from typing import Optional, Tuple, Union
from . import Tensor

def det(input: Tensor) -> Tensor: ...
def inv(input: Tensor) -> Tensor: ...
def solve(input: Tensor, other: Tensor) -> Tensor: ...
def norm(input: Tensor, ord: Union[int, float, str, None] = None, dim: Optional[Union[int, Tuple[int, ...]]] = None, keepdim: bool = False) -> Tensor: ...
def svd(input: Tensor, full_matrices: bool = True) -> Tuple[Tensor, Tensor, Tensor]: ...
def eig(input: Tensor) -> Tuple[Tensor, Tensor]: ...
def eigh(input: Tensor) -> Tuple[Tensor, Tensor]: ...
def eigvals(input: Tensor) -> Tensor: ...
def eigvalsh(input: Tensor) -> Tensor: ...
def qr(input: Tensor) -> Tuple[Tensor, Tensor]: ...
def cholesky(input: Tensor) -> Tensor: ...
def matrix_rank(input: Tensor, tol: Optional[float] = None) -> Tensor: ...
def matrix_power(input: Tensor, n: int) -> Tensor: ...
def cross(input: Tensor, other: Tensor, dim: int = -1) -> Tensor: ...
def pinv(input: Tensor) -> Tensor: ...
def lstsq(input: Tensor, b: Tensor) -> Tuple[Tensor, Tensor, Tensor, Tensor]: ...
def multi_dot(tensors: list[Tensor]) -> Tensor: ...
def vecdot(x: Tensor, y: Tensor, dim: int = -1) -> Tensor: ...
def diagonal(input: Tensor, offset: int = 0, dim1: int = -2, dim2: int = -1) -> Tensor: ...
